export const NAVBAR_GET_CATEGORIES_BEGIN = 'NAVBAR_GET_CATEGORIES_BEGIN';
export const NAVBAR_GET_CATEGORIES_SUCCESS = 'NAVBAR_GET_CATEGORIES_SUCCESS';
export const NAVBAR_GET_CATEGORIES_FAILURE = 'NAVBAR_GET_CATEGORIES_FAILURE';
export const NAVBAR_GET_CATEGORIES_DISMISS_ERROR = 'NAVBAR_GET_CATEGORIES_DISMISS_ERROR';
